feat: OkHttp implementation for making HTTP calls and WebSocket connections
ably/ably-java pull request #1035
Opened 2024-09-25 11:41 UTC by ttypic

2024-10-01 08:16 UTC, sacOO7 commented on network-client-okhttp/src/main/java/io/ably/lib/network/OkHttpWebSocketEngineFactory.java
> +    @Override
Can we rename `WebsocketEngineFactory` to `WebsocketClientFactory`. This should also be reflected across all interface impl. `WebsocketEngineFactory` term feels confusing.

2024-10-01 08:19 UTC, sacOO7 commented on network-client-okhttp/src/main/java/io/ably/lib/network/OkHttpWebSocketEngine.java
> +public class OkHttpWebSocketEngine implements WebSocketEngine {
Rename to 
`OkHttpWebSocketClient implements AblyWebsocketClient`

2024-10-01 18:40 UTC, sacOO7 requested changes
Can we add integration tests for OkHttp proxy? 
Also, it will be great if we can have OkHttp integration tests running ( for both rest and realtime ) by enabling some type of flag on CI ?

2024-10-03 10:37 UTC, ttypic commented on lib/src/main/java/io/ably/lib/transport/WebSocketTransport.java
> +                webSocketClient = this.webSocketEngine.create(wsUri, new WebSocketHandler(this::receive));
this code is inside constructor, so no need to synchronize here

2024-10-07 12:09 UTC, sacOO7 approved these changes
LGTM, Btw, you can take a look at RabbitAI comments?
Some of those look sensible to implement

2024-10-07 14:46 UTC, merged