Increase minimum SDK version to Android 16
ably/ably-java pull request #691
Opened 2021-07-29 11:14 UTC by KacperKluka

After recent upgrade in Firebase version the android build is failing because the `minSdkVersion` is too low. I updated it to the minimal required version `16` but in the future we could consider increasing it to some newer versions like `19`.
```
Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.google.firebase:firebase-messaging:22.0.0] /Users/runner/.gradle/caches/transforms-2/files-2.1/b39a806af3e38e8d80a3a7e52816e28b/AndroidManifest.xml as the library might be using APIs not available in 14
  	Suggestion: use a compatible library with a minSdk of at most 14,
  		or increase this project's minSdk version to at least 16,
  		or use tools:overrideLibrary="com.google.firebase.messaging" to force usage (may lead to runtime failures)
```

2021-07-29 12:09 UTC, QuintinWillison approved these changes

2021-07-29 12:10 UTC, QuintinWillison requested changes
Oops, sorry, withdrawing my approval as just noticed you also need to update the readme. Perhaps grep for `14`?

2021-07-30 05:37 UTC, QuintinWillison approved these changes

2021-07-30 08:35 UTC, AndyNicks approved these changes

2021-07-30 09:27 UTC, merged