Use the "maven-publish" plugin for publishing the SDKs
ably/ably-java pull request #781
Opened 2022-05-17 06:50 UTC by KacperKluka

I've removed the old and deprecated `maven` plugin and used `maven-publish` instead. The setup is almost identical with an exception that I've removed the support for zipping the release files as it feels unnecessary to do this, since the plugin is responsible for all the packaging and publishing work. I've also updated the contributing guide to use the new plugin.

2022-06-21 06:52 UTC, qsdigor approved these changes

2022-06-21 10:45 UTC, QuintinWillison requested changes
I just tried these commands on my local system but got

> `Cannot perform signing task ':java:signReleasePublication' because it has no configured signatory`

and

> `Cannot perform signing task ':android:signReleasePublication' because it has no configured signatory`

respectively:

```
ably-java % ./gradlew java:publish

> Task :initializeSonatypeStagingRepository
Created staging repository 'ioably-1031' at https://oss.sonatype.org/service/local/repositories/ioably-1031/content/

> Task :java:javadoc
/Users/quintinwillison/code/ably/ably-java/java/src/main/java/io/ably/lib/rest/AblyRest.java:20: warning - @param argument "key;" is not a parameter name.
/Users/quintinwillison/code/ably/ably-java/java/src/main/java/io/ably/lib/rest/AblyRest.java:30: warning - @param argument "options:" is not a parameter name.
2 warnings

> Task :java:signReleasePublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':java:signReleasePublication'.
> Cannot perform signing task ':java:signReleasePublication' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
16 actionable tasks: 8 executed, 8 up-to-date
?1 ably-java % ./gradlew android:publish

> Task :initializeSonatypeStagingRepository
Created staging repository 'ioably-1032' at https://oss.sonatype.org/service/local/repositories/ioably-1032/content/

> Task :android:javadoc
/Users/quintinwillison/code/ably/ably-java/android/src/main/java/io/ably/lib/platform/AndroidPlatform.java:46: warning - @return tag has no arguments.
1 warning

> Task :android:signReleasePublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:signReleasePublication'.
> Cannot perform signing task ':android:signReleasePublication' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
36 actionable tasks: 7 executed, 29 up-to-date
```

Is this something I need to change in my environment, or might it be something wrong in the changes made here? 🤔

2022-06-21 10:53 UTC, KacperKluka commented
@QuintinWillison in order to publish you need to sign the SDKs and in order to do that you have to provide [those 3 secrets](https://github.com/ably/ably-java/pull/781/files#diff-4ec10152d878d2c431fb83b5a8a3651d3fae7e551c7a8b389666fb158e9b0cb0R114-R116) (they should be already in the CI)
- SIGNING_KEY_ID
- SIGNING_KEY_BASE64
- SIGNING_PASSWORD

2022-06-21 13:21 UTC, QuintinWillison commented
I discussed this earlier with @KacperKluka via direct messaging, to confirm with him that my local environment is set up correctly for releases for both `io.ably` and `com.ably` (my Sonatype user has been added to both projects for OSSRH). My user Gradle properties (`~/.gradle/gradle.properties`) include (with redactions so I could share here, in this public issue):

```
# For ably-java release process.
signing.keyId=[REDACTED]
signing.password=[REDACTED]
signing.secretKeyRingFile=/Users/quintinwillison/[REDACTED]
ossrhUsername=[REDACTED]
ossrhPassword=[REDACTED]
```

It seems that I am also likely to need the changes up to and include those in https://github.com/ably/ably-java/pull/782 in order for this to work for me.

2022-06-22 07:48 UTC, QuintinWillison approved these changes

2022-06-23 05:39 UTC, merged