Enable and fix ignored tests
ably/ably-java pull request #867
Opened 2022-11-24 15:08 UTC by qsdigor

This is PR for all those issues related to failing, flaky or disabled tests.

In the spirit of fixing tests, I have realized that the workflow for testing them was not optimized if only one test fails the whole test suite for REST and Realtime fails. We usually want to try to re-run only that set of test so I have splitted REST and Realtime tests in two separate jobs and they will run in sequence. If one of them fail we can re-run it. 
I have also added submodule loading which was previously missing and was necessary for some tests.

2022-11-24 15:23 UTC, QuintinWillison requested changes
As described in [this Slack message (internal)](https://ably-real-time.slack.com/archives/C019LDWM9UH/p1669300176865719?thread_ts=1669122138.769479&cid=C019LDWM9UH) for the CI workflows the idiomatic fix is to instruct the checkout action to recursively checkout submodules.

2022-11-24 15:44 UTC, qsdigor commented
> 

I have changed the way submodules are loaded here https://github.com/ably/ably-java/pull/867/commits/d8e27d2eeacfe8153678ab961c5cad7da43d57bc

2022-11-28 08:16 UTC, QuintinWillison approved these changes

2022-11-28 08:16 UTC, QuintinWillison commented on lib/src/test/java/io/ably/lib/test/realtime/RealtimeMessageTest.java
> +            // publish and await success
Perhaps clearer to adjust this comment:

```suggestion
            // publish and await expected failure (completion with error)
```

2022-12-02 13:50 UTC, KacperKluka approved these changes
I only briefly checked the changes but given the amount of removed `@Ignore` annotations from tests and the fact that the CI is green everything seems to be working 👍 Thanks for taking care of it 🙇

2022-12-21 12:17 UTC, ikbalkaya requested changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/HttpTest.java
> +import io.ably.lib.util.PlatformAgentProvider;
Please revert import changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/HttpTest.java
> -         */
I think you should keep this

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/HttpTest.java
> -            urlHostArgumentStack.get(i).matches(PATTERN_HOST_FALLBACK);
Also why was this removed?

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/RestAuthAttributeTest.java
> +
Please revert un-needed import changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/RestAuthAttributeTest.java
> +                Thread.sleep(3000L);
I wonder what was the idea behind changing those values

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/RestChannelBulkPublishTest.java
> -import static org.junit.Assert.fail;
import changes ...

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/RestChannelHistoryTest.java
> +
import changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/test/rest/RestPushTest.java
> -import java.util.concurrent.CopyOnWriteArraySet;
import changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/util/CryptoMessageTest.java
> +
import changes

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/util/CryptoMessageTest.java
> +        final CipherParams cParams = Crypto.getParams(algorithm, fixtureSet.key, fixtureSet.iv);
`cipherParams`

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/util/CryptoMessageTest.java
> +        final CipherParams cParams = Crypto.getParams(algorithm, fixtureSet.key, fixtureSet.iv);
`cipherParams`

2022-12-21 12:17 UTC, ikbalkaya commented on lib/src/test/java/io/ably/lib/util/CryptoTest.java
> +import java.util.Arrays;
import changes

2022-12-22 08:48 UTC, qsdigor commented on .github/workflows/check.yml
> +        run: ./gradlew checkstyleMain checkstyleTest checkWithCodenarc runUnitTests
Description is updated. Thank you

2022-12-23 10:39 UTC, QuintinWillison commented on .github/workflows/check.yml
> +        run: ./gradlew checkstyleMain checkstyleTest checkWithCodenarc runUnitTests
I'm resolving this conversation on @ikbalkaya's behalf.

2022-12-23 10:42 UTC, QuintinWillison commented on lib/src/test/java/io/ably/lib/test/realtime/ConnectionManagerTest.java
> +
Arbitrary sleeps are a testing anti-pattern that I would rather not see being patched into existing tests in order to make them pass. We need to understand what isn't being waited upon sufficiently and fix that.

2024-07-03 11:18 UTC, closed without merging