Error log stack traces
ably/ably-java pull request #964
Opened 2023-07-13 16:01 UTC by AndyTWF

Replaces a number of places where exception information is sent to the system error log rather than custom error handlers that users may be using.

2023-07-13 16:46 UTC, sacOO7 commented on lib/src/main/java/io/ably/lib/http/HttpCore.java
> -            ioe.printStackTrace();
aren't we supposed to use logger here?

2023-07-13 16:47 UTC, sacOO7 commented on lib/src/main/java/io/ably/lib/http/HttpCore.java
> -            ioe.printStackTrace();
atleast send a warning message

2023-07-13 18:34 UTC, sacOO7 commented on lib/src/main/java/io/ably/lib/http/HttpCore.java
> -            ioe.printStackTrace();
Got it 👍

2023-07-13 18:37 UTC, sacOO7 commented
I can see repeated checks for 
```
if (Log.level <= Log.VERBOSE) {
Log.v(
```
Isn't this supposed to get handled as a part of `Log.v()` impl itself

2023-07-13 18:56 UTC, sacOO7 requested changes
@AndyTWF It seems we are using a Singleton logger instance. This can lead to a buggy situation where

1. If the app is using more than one instance of `AblyRealtime` and is providing multiple logHandlers as a part of clientOptions.
2. Last assigned `logHandler` will get be set at https://github.com/ably/ably-java/blob/28ffd6b20fa1adc0ae64adb4cf105b2fb5fda416/lib/src/main/java/io/ably/lib/util/Log.java#L143C6-L143C6.
3. So, all of the logs will get mixed and only be available to the last handler. 
4. Afaik, we don't have singleton loggers in other SDKs to avoid situations like these. 
5. As per spec, `LogLevel` and `LogHandler` are supposed to be passed from `clientOptions` and the same handler should be used to log the errors. There shouldn't be a case for overriding LogLevel/handlers for multiple `AblyRealtime` instances.

2023-07-13 19:07 UTC, AndyTWF commented
> @AndyTWF It seems we are using a [Singleton logger instance](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/util/Log.java). This can lead to a buggy situation where
> 
> 1. If the app is using more than one instance of `AblyRealtime` and is providing multiple logHandlers as a part of clientOptions.
> 2. Last assigned `logHandler` will get be set at https://github.com/ably/ably-java/blob/28ffd6b20fa1adc0ae64adb4cf105b2fb5fda416/lib/src/main/java/io/ably/lib/util/Log.java#L143C6-L143C6.
> 3. So, all of the logs will get mixed and only be available to the last handler.
> 4. Afaik, we don't have singleton loggers in other SDKs to avoid situations like these.
> 5. As per spec, `LogLevel` and `LogHandler` are supposed to be passed from `clientOptions` and the same handler should be used to log the errors. There shouldn't be a case for overriding LogLevel/handlers for multiple `AblyRealtime` instances.

Yes this is something we've been aware of for a while - I'd propose we do this in a separate branch though, as it's not an insignificant amount of work to un-static everything :)

2023-07-13 19:13 UTC, sacOO7 commented
> 

@AndyTWF maybe this can be done as a part of this PR. It should be a small work to replace the checks, wdyt ?

2023-07-13 19:13 UTC, AndyTWF commented
Comments to explain verbose logging done in 5176e80a

2023-07-13 19:16 UTC, sacOO7 commented
> Comments to explain verbose logging done in [5176e80](https://github.com/ably/ably-java/commit/5176e80af769a04fcb481b1217c99beac3fa5db7)

mm.. the message is not that clear, can we make it like 
```
Verbose LogLevel check avoids extra computation cycles needed to build the logging message.
```

2023-07-17 11:46 UTC, owenpearson approved these changes
LGTM 👍

2023-07-17 13:11 UTC, sacOO7 approved these changes
LGTM

2023-07-17 13:15 UTC, merged